### ISSUE TITLE
Special characters (accents)

### ISSUE THREAD

**Issue by elb0** [hodgettsp/cesR#1] opened 2020-10-06 00:03 UTC
Hi Paul!
I've been playing with ces2019_web,  but after running to_factor() the special characters for French accents (like 
Bloc Québécois or François Legault) are causing me issues. I can't run glimpse() or skimr::skim() etc. because they can't cope with these characters. I don't know if this a particular Mac encoding issues, but figured I'd reach out because I don't think I'd be the only person to encounter this. Any ideas for easy fixes?
Thanks!
Liza (Department of Statistical Sciences, U of T)

**Comment by RohanAlexander** [comment] 2020-10-12 20:25
Dear @elb0 ,

Thank you for identifying an important issue and the clear directions for reproducing it.
I think that we can fix this.

@hodgettsp we need to be explicit about the text encoding for the haven::read_dta() call. It looks like adding an encoding argument means the French accents are carried through (on my Mac). I'll update these and then push an update, but can you please check that they then still run on your machine (not a Mac ;) ). If so, then can you please close the issue.

Rohan

**Comment by RohanAlexander** [comment] 2020-10-12 20:56
I've pushed an update. It looks like the accents are fine e.g. (after running to_factor) 
ces2019_web$cps19_imp_loc_iss_p %>% unique() 
displays the accents.

@hodgettsp can you please double check and then close the issue if you're happy :)

**Comment by hodgettsp** [comment] 2020-10-13 00:07
Thank you for reaching out @elb0! And thanks for testing out cesR!

I've checked the fix that @RohanAlexander pushed and it looks like it's working on Windows. Thanks for getting to this @RohanAlexander. I didn't receive a notification from GitHub so I'm going to have to check my settings. I also double-checked that the other surveys work with the described problem. Everything seems to be working so I'll close this issue.

Thanks!

**Closed as completed by hodgettsp** 2020-10-13 00:07 UTC
Labels: bug
